import type { Metadata } from "next";

import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "@/components/Provider"
import { Toaster } from "sonner";
// import LoadScript from "@/components/LoadScript";
import { VoiceProvider } from '@/components/VoiceContext'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="min-h-screen bg-gradient-to-br from-indigo-50 via-white to-purple-50 dark:from-gray-900 dark:via-gray-800 dark:to-gray-900">
          <Provider>
            <VoiceProvider>
              {/* <LoadScript /> */}
              {children}
            </VoiceProvider>
            <Toaster />
          </Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
